<?php

if( function_exists('acf_add_local_field_group') ):

	acf_add_local_field_group(array (
		'key' => 'group_58f76fa15da9e',
		'title' => 'Home Programs Section',
		'fields' => array (
			array (
				'multiple' => 0,
				'allow_null' => 0,
				'choices' => array (
					'left' => 'left',
					'center' => 'center',
				),
				'default_value' => array (
					0 => 'left',
				),
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'return_format' => 'value',
				'key' => 'field_58f791953893a',
				'label' => 'Text Alignment',
				'name' => 'text_alignment',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'multiple' => 0,
				'allow_null' => 0,
				'choices' => array (
					2 => '2',
					3 => '3',
				),
				'default_value' => array (
					0 => 2,
				),
				'ui' => 0,
				'ajax' => 0,
				'placeholder' => '',
				'return_format' => 'value',
				'key' => 'field_58f791f99dc64',
				'label' => 'Columns',
				'name' => 'columns',
				'type' => 'select',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
			array (
				'sub_fields' => array (
					array (
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'key' => 'field_58f78e65018df',
						'label' => 'Heading',
						'name' => 'heading',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array (
						'return_format' => 'array',
						'preview_size' => 'thumbnail',
						'library' => 'all',
						'min_width' => 554,
						'min_height' => 332,
						'min_size' => '',
						'max_width' => '',
						'max_height' => '',
						'max_size' => '',
						'mime_types' => '',
						'key' => 'field_58f78f81018e0',
						'label' => 'Image',
						'name' => 'image',
						'type' => 'image',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array (
						'default_value' => '',
						'maxlength' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'key' => 'field_58f792e226510',
						'label' => 'Link',
						'name' => 'link',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
					array (
						'default_value' => '',
						'new_lines' => 'wpautop',
						'maxlength' => '',
						'placeholder' => '',
						'rows' => '',
						'key' => 'field_58f792fb26511',
						'label' => 'Description',
						'name' => 'description',
						'type' => 'textarea',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array (
							'width' => '',
							'class' => '',
							'id' => '',
						),
					),
				),
				'min' => 1,
				'max' => 0,
				'layout' => 'row',
				'button_label' => 'Add Program',
				'collapsed' => '',
				'key' => 'field_58f78e54018de',
				'label' => 'Programs',
				'name' => 'programs',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array (
					'width' => '',
					'class' => '',
					'id' => '',
				),
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'post_type',
					'operator' => '==',
					'value' => 'page',
				),
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => AG_EXTRES_TEMPLATE_PATH . '/home.php',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => 1,
		'description' => '',
	));

endif;
